### ISSUE TITLE
conflict between powermock and nondex

### ISSUE THREAD

**Issue by romani** [TestingResearchIllinois/NonDex#112]
Details: https://github.com/checkstyle/checkstyle/pull/3658 , travis have full log.
UTs pass without problems. Nondex validation fails.
Yes our UT is far from ideal, and use reflection to reach 100% coverage.
Problem appear only as powermock is introduced to this class:
```
@RunWith(PowerMockRunner.class)
@PrepareForTest({DefaultConfiguration.class, ConfigurationLoader.class})
```

steps to reproduce:
```
git clone https://github.com/checkstyle/checkstyle.git
git checkout i3657-exception-logging
mvn nondex:nondex
```

output:
```
Tests run: 1, Failures: 0, Errors: 1, Skipped: 0, Time elapsed: 1.688 sec <<< FAILURE! - in com.puppycrawl.tools.checkstyle.ConfigurationLoaderTest
testIncorrectTag(com.puppycrawl.tools.checkstyle.ConfigurationLoaderTest)  Time elapsed: 0.295 sec  <<< ERROR!
java.lang.IllegalArgumentException: argument type mismatch
	at com.puppycrawl.tools.checkstyle.ConfigurationLoaderTest.testIncorrectTag(ConfigurationLoaderTest.java:393)
```

If there a way to do skip this test in nondex during investigation of problem ? 
I do not want to block my PR for long time

**Comment by alexgyori** [comment]
The easiest way at this point is to use the -Dexclude as a command line argument when running mvn nondex:nondex (basically calls surefire and this is the exclude for surefire) and then the test should not be run by nondex.

We have some annotation that you can add on a test class to exclude it from nondex, but that's not yet released (will release it soon -- there's some regression with it).

Thanks for the detailed bug report. I see the failure is triggered in commit 235bb8333e7be7c4c6b4c5af46f16555edfd7abf. I will debug this next week and patch it in the next release.

**Comment by romani** [comment]
I merged PR in checkstyle repo, and update CI to skip this test , so you do not need to do any checkout to branch.

steps to reproduce:
```
git clone https://github.com/checkstyle/checkstyle.git
mvn nondex:nondex
```

**Comment by rnveach** [comment]
Just as FYI.
> java.lang.IllegalArgumentException: argument type mismatch

checkstyle backport 7.4 (not yet released) is getting this exception now, without running nondex. It uses JDK6 and Eclipse by running tests through JUnit.

checkstyle (7.4) gets it only running nondex. JDK8 and Eclipse and JUnit do not produce the issue.
It could be related to some system class version in nondex?

**Comment by romani** [comment]
code was refactored on checkstyle side.
build is passing. 
issue is resolved.
