### ISSUE TITLE
[BUG] NonDex does not run tests in clean

### ISSUE THREAD

**Issue by alexgyori** [TestingResearchIllinois/NonDex#85]
NonDex does not run tests in the dry run.
The 1.1.1 release runs the tests in clean, but the current head doesn't.

If I remove the call to the method adding the exclude groups to the config, then everything is back to normal and tests run also in clean.

**Comment by alexgyori** [comment]
@azy2 can you take a look and see if you spot some obvious issue?

**Comment by azy2** [comment]
#113
